# Change these first
owner: gildlab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DA B 2
    url: https://gildlab-ipfs-5.eu.ngrok.io/api/v0/version
    method: POST
  - name: DF B 1
    url: https://ipfs.dragonflysun.ge/api/v0/version
    method: POST
  - name: DA B 1
    url: https://db1.gildlab.xyz/api/v0/version
    method: POST
  - name: V B
    url: https://gildlab-ipfs-0.in.ngrok.io/api/v0/version
    method: POST
  # ipfs.io seems to rate limit us somehow making it hard to check
  # - name: Some hash
  #   url: https://ipfs.io/ipfs/QmYVXD6CCYEC7y5jz2rTkadiqFcDby3Xoy4q4x6RGXCAUN
  - name: stf website
    url: https://sft.gildlab.xyz
  - name: gl website
    url: https://gildlab.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.gildlab.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Gildlab IPFS nodes uptime
  introTitle: "**Gildlab IPFS Nodes uptime"
  introMessage: This page is tracking the status of known Gildlab IPFS nodes.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
